### ISSUE TITLE
test/test-repl-domain.js fails because core's repl requires core's domain module

### ISSUE THREAD

**Issue by misterdjules** [misterdjules/domaine#3]
```
$ node test/test-repl-domain.js 
Error: Uncaught exception capture callback not available
    at Object.<anonymous> (/Users/jgilli/dev/domaine/index.js:88:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)

$ 
```

This is basically a manifestation of https://github.com/misterdjules/domaine/issues/2.

**Comment by misterdjules** [comment]
Fixed by https://github.com/misterdjules/domaine/commit/433236aacb0a3e1b24ffd5cf9dbf05ff629092e0  which depends on a custom branch of node that can be found at https://github.com/misterdjules/node-1/tree/support-multiple-exception-capture-cb.
